// Generated by https://quicktype.io

export interface IForm {
  form: Field[]
}

export interface Field {
  id: number
  type: string
  name: string
  label: string
  value: string
  options?: Option[]
  validations: Validation[]
}

export interface Option {
  id: number
  value: string
  label: string
}

export interface Validation {
  type: string
  value?: number
}
