// Generated by https://quicktype.io

export interface IForm {
  form: Field[]
}

export interface Field {
  id: number
  type: FieldType
  name: string
  label: string
  value: string
  options?: OptionField[]
  validations: Validation[]
}

export interface OptionField {
  id: number
  value: string
  label: string
}

export interface Validation {
  type: ValidationType
  value?: number
}
export enum ValidationType {
  REQUIRED = 'required',
  MAX_LENGTH = 'maxLength'
}

export enum FieldType {
  SELECT = 'select',
  INPUT = 'input',
  TEXT_AREA = 'text-area',
  DATE_PICKER = 'date-picker',
  FILE = 'file'

}
